# Generated by Django 5.2.8 on 2026-03-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_category_project_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontent',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='generalcontent',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalcontent',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='generalcontent',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
