# Generated by Django 5.2.8 on 2026-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_generalcontent_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalcontent',
            name='badge_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalcontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='generalcontent',
            name='trust_indicator_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
