# Generated by Django 5.2.8 on 2026-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_about_blog_contactmessage_herosection_projectimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume_static',
            field=models.CharField(blank=True, help_text="Path to static resume file (e.g. 'portfolio/pdf/resume.pdf')", max_length=200, null=True),
        ),
    ]
