# Generated by Django 5.2.8 on 2026-09-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_about_resume_static'),
        ('portfolio', '0006_sitesettings_contact_email_sitesettings_location_and_more'),
    ]

    operations = [
    ]
