# Generated by Django 5.2.8 on 2026-09-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_merge_20260917_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='resume_static',
        ),
    ]
